### ISSUE TITLE
about covariates 

### ISSUE THREAD

**Issue by Yoledou** [Poissonfish/iPat#10]
If my fixed effects are gender and season,(like 0 for female, 1 for male and 0 for winter 1 for summer 
Taxa	gneder	season
ID1	1	        1
ID2	1	        1
ID3	0              0
they will be treated as covariates in the BGLR method. How can it be converted into a format recognized by ipat
Taxa	Cov1	  Cov2
ID_1	3.617538	  -0.9368706
ID_2	0.888413	  -0.0546190
ID_3	-1.276830   0.2140963)
thanks a lot !

**Comment by Poissonfish** [comment]
Hi, thanks for the question. How about removing the "taxa column" and give it a try? The covariate file in our demo data should serve as your reference.
