### ISSUE TITLE
Demo file cannot run

### ISSUE THREAD

**Issue by Yoledou** [Poissonfish/iPat#11]
Dear  James 
I am a windows user and downloaded the latest R3.6.3, 
then using source ("http://zzlab.net/iPat/iPat_installation.r") to install the packages that ipat need.
All the packages are installed and the required packages are carefully checked, but when I run the 'case2 demo file', the running box is blank and there is nothing, what is wrong?
Thanks a lot!!

**Comment by Poissonfish** [comment]
Hi, 
Thank you for your update. Is was my mistake while updating iPat. It should work fine now, please try it again and welcome to post issues if you still find anything wrong.

**Comment by Yoledou** [comment]
Dear James
I try to run the 'case2 demo file' again but the running box is still blank and there is nothing in the box, could you please give me some advice? You said that you update the ipat and should I re-download the ipat.zip once again?

**Comment by Poissonfish** [comment]
Sorry for the confusion.
Yes, please re-download it from website zzlab.net/iPat. Thank you.

**Comment by Yoledou** [comment]
OK! thanks a lot I'll try it right now

**Comment by Yoledou** [comment]
Dear James 
Thank you for your patient answers. It was still nothing in the box. I guess if I haven't installed anything less, but according to the prompt, the java and the R package that have to be installed have already been installed. Could you help me operate it remotely?

**Comment by Poissonfish** [comment]
Ok, would you like to send some screenshot of the prompt to my email: chun-peng.chen@wsu.edu?
And sure, I can' try to reach you through Zoom if necessary.

**Comment by Yoledou** [comment]
Thanks a lot I'll send you some screenshot right now

**Comment by Yoledou** [comment]
Dear James
The email for help has been sent to chun-peng.chen@wsu.edu, please check！
