### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by ZhangZhiwu** [Poissonfish/iPat#2]
Hi James

Could you please add some tutorials on using different combinations of data formats and methods?

Thank you.

Zhiwu

**Comment by Poissonfish** [comment]
Dear Zhiwu, 
I just updated the tutorial section in the section 4: "Case study: Perform GWAS-assisted GS by FarmCPU and BGLR (Format: VCF)". Hope it'd be helpful and I'll keep update some another examples in the recent future. Thanks for your feedback!

James

**Comment by ZhangZhiwu** [comment]
Thank you.

Zhiwu Zhang, Ph.D.
WGC Distinguished Professorship for Statistical Genomics
105 Johnson Hall, Department of Crop and Soil Sciences
Washington State University
Pullman, WA 99164, USA<x-apple-data-detectors://1/1>

Phone (Office): 509-335-2899<tel:509-335-2899>
Phone (Lab): 509-335-4551<tel:509-335-4551>
Website (Personal): http://css.wsu.edu/zhiwu-zhang
Website (Lab): http://zzlab.net<http://zzlab.net/>
Email: Zhiwu.Zhang@wsu.edu<mailto:Zhiwu.Zhang@wsu.edu>
