### ISSUE TITLE
Blank "run" screen

### ISSUE THREAD

**Issue by jjstocks** [Poissonfish/iPat#3]
Hi, I'm a windows user and I've installed R 3.4.3 with all the necessary packages from the link and also java 8 update 161.

I downloaded iPat, demo data and all the steps are working (using plink demo files and just GWAS) up until "run" where it stops and outputs a blank word file and an .err file. 

Any ideas what I'm doing wrong?
Many thanks

**Comment by Poissonfish** [comment]
Hi,
Could you attach the screen shot of iPat window and paste the log message that generated from it?

Thank you,
James

**Comment by jjstocks** [comment]
![presentation1](https://user-images.githubusercontent.com/36296161/36159053-b2a046e6-10d5-11e8-9c34-fd8c0abb4418.jpg)

[Project_2.log](https://github.com/Poissonfish/iPat/files/1720550/Project_2.log)

**Comment by Poissonfish** [comment]
It might be resulted from
 1.) "a space" within one of your file path. 
 2.) Try to reinstall the required packages in R by running `source("http://zzlab.net/iPat/iPat_installation.r")` 

And I just released an update of iPat. To ensure the stability, please try to download it from: [zzlab](http://zzlab.net/iPat/) and see if it works. Thank you.
