### ISSUE TITLE
ipat.exe not executable

### ISSUE THREAD

**Issue by wzxsoy** [Poissonfish/iPat#5]
Hi there,
I'm a windows user (Dell T7500)and I've installed R 3.5.0  with all the necessary packages from the link and also java 10 .
When I double click ipat.exe ,  the computer just has no reaction.  It seems like the ipat.exe is not executable. Any help ?

Wen

**Comment by bigshrimp123** [comment]
I hava the same problem!

**Comment by bigshrimp123** [comment]
if you have slove it,please tell me how to slove it.
thanks!

**Comment by Poissonfish** [comment]
Hi, it's likely due to non-R folders existing in "C://Program Files/R", since iPat will look for the latest version of R and would encounter issues with those folders. Anyway, just got it fixed. Please re-download iPat from [here](zzlab.net/iPat/iPat.zip) and see if it works out.

**Comment by ukelektra** [comment]
Hi i am also a window user with the same problem, at first when i downloaded the ipat folder, the  executable file “iPat.exe” did not work, it was unresponsive. 
I deleted and downloaded again, now the downloaded IPAT folder has no executable file only the "res" folder is in it. I have updated version of R also and have run the codes as stated in the manual.
What do i do?

**Comment by Poissonfish** [comment]
Thanks for your feedback. Would you like to try using the command-line environment so that we can know the error message? 

Here’re detailed steps you can do:
1. Download .jar of iPat: [here](http://zzlab.net/iPat/iPatJar.zip)
2. Unzip it and put it in your desktop 
3. Open ‘Command Prompt’ and change your working directory by giving the command “cd Desktop”
4. Launch iPat by the order “java -jar iPat/iPat.jar”

You should be able to see the error message from it. Please let me know what you got so that I can try to fix it. Thank you!

**Comment by ukelektra** [comment]
Hi this is the message i am getting
C:\temp\iPatJar>java -jar iPat\iPat.jar
Exception in thread "main" java.lang.NullPointerException
        at iPat.getREXC(iPat.java:89)
        at iPat.<init>(iPat.java:29)
        at main.main(main.java:13)

**Comment by Poissonfish** [comment]
it's probably because your R wasn't installed in a default path: C://Program Files/R. Would you like to reinstall it and have R installed in a default path?

**Comment by ukelektra** [comment]
Thanks for the reply. please could you check the download file publicly available, the one i am downloading only has the "res" folder and no executable file. Cheers

**Comment by Poissonfish** [comment]
Hi thanks for the report and sorry for the mistake. Just uploaded a correct one : [iPat.exe](http://zzlab.net/iPat/iPat.zip).

Meanwhile, I'm working on a new feature that iPat will prompt users for R installation path if iPat.exe can't be launched normally on Windows.
