### ISSUE TITLE
Error in library(R.utils): there is no package called 'R.utils'

### ISSUE THREAD

**Issue by AbbyKimball** [Poissonfish/iPat#9]
Hello! 

I was trying to analyze my data using the PLINK method in iPat, but got the following error:

`Error in library(R.utils): there is no package called 'R.utils'`

Thanks!

**Comment by Poissonfish** [comment]
Hi Abby,

Have you tried running `source("http://zzlab.net/iPat/iPat_installation.r")` in R console first to install the dependencies?
You can learn further details from the page: http://poissonfish.github.io/iPat/get-started.html

**Comment by AbbyKimball** [comment]
Thank you so much for your quick reply. Now that the error is resolved I am getting this error:

`Error in data.frame(taxa, rawGenotype)`

Does this indicate a problem with my genotype file? Thanks!!!

**Comment by Poissonfish** [comment]
You might wanna compare your PED file with the [demo data](http://zzlab.net/iPat/demo.zip). The folder "Case 1" should contain the demo format for your case.
